apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kraftivibe

namePrefix: prod-

resources:
  - ../../base

labels:
  - pairs:
      environment: production

patches:
  - path: patch-api-deployment.yaml
    target:
      kind: Deployment
      name: kraftivibe-api

replicas:
  - name: kraftivibe-api
    count: 3

images:
  - name: kraftivibe/api
    newTag: latest
