apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kraftivibe

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-statefulset.yaml
  - redis-statefulset.yaml
  - minio-deployment.yaml
  - api-deployment.yaml
  - ingress.yaml
  - hpa.yaml

labels:
  - pairs:
      app.kubernetes.io/name: kraftivibe
      app.kubernetes.io/part-of: kraftivibe
